--AIRLINE DELAYS
SELECT A.AIRPORT
       ,MIN('DEPARTURE') AIRPORT_ORIGIN
       ,SUM(CASE WHEN IFNULL(AIR_SYSTEM_DELAY,0) > 0  THEN 1 ELSE 0 END) AIR_SYSTEM_DELAY
       ,SUM(CASE WHEN IFNULL(SECURITY_DELAY,0) > 0 THEN 1 ELSE 0  END) SECURITY_DELAY
       ,SUM(CASE WHEN IFNULL(AIRLINE_DELAY,0) > 0 THEN 1 ELSE 0  END) AIRLINE_DELAY
       ,SUM(CASE WHEN IFNULL(LATE_AIRCRAFT_DELAY,0) > 0 THEN 1 ELSE 0  END) LATE_AIRCRAFT_DELAY
       ,SUM(CASE WHEN IFNULL(WEATHER_DELAY,0) > 0 THEN 1 ELSE 0  END) WEATHER_DELAY
FROM DW.FACT_FLIGHTS F JOIN DW.DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_KEY = A.AIRPORT_KEY
GROUP BY A.AIRPORT
UNION ALL
SELECT A.AIRPORT
       ,MIN('DESTINATION') AIRPORT_ORIGIN
       ,SUM(CASE WHEN IFNULL(AIR_SYSTEM_DELAY,0) > 0  THEN 1 ELSE 0 END) AIR_SYSTEM_DELAY
       ,SUM(CASE WHEN IFNULL(SECURITY_DELAY,0) > 0 THEN 1 ELSE 0  END) SECURITY_DELAY
       ,SUM(CASE WHEN IFNULL(AIRLINE_DELAY,0) > 0 THEN 1 ELSE 0  END) AIRLINE_DELAY
       ,SUM(CASE WHEN IFNULL(LATE_AIRCRAFT_DELAY,0) > 0 THEN 1 ELSE 0  END) LATE_AIRCRAFT_DELAY
       ,SUM(CASE WHEN IFNULL(WEATHER_DELAY,0) > 0 THEN 1 ELSE 0  END) WEATHER_DELAY
FROM DW.FACT_FLIGHTS F JOIN DW.DIM_AIRPORTS A ON F.DESTINATION_AIRPORT_KEY = A.AIRPORT_KEY
GROUP BY A.AIRPORT
ORDER BY AIRPORT;

--MOST UNIQUE ROUTES
SELECT MUR.AIRLINE
       ,MUR.TOTAL_UNIQUE_ROUTES
       ,RANK() OVER(ORDER BY TOTAL_UNIQUE_ROUTES DESC) RANK
FROM(
SELECT AIRLINE, COUNT(*) TOTAL_UNIQUE_ROUTES
FROM(
SELECT A.AIRLINE,DEPARTURE_AIRPORT_KEY,DESTINATION_AIRPORT_KEY
FROM DW.FACT_FLIGHTS F JOIN DW.DIM_AIRLINES A ON F.AIRLINE_KEY = A.AIRLINE_KEY
GROUP BY A.AIRLINE,DEPARTURE_AIRPORT_KEY,DESTINATION_AIRPORT_KEY) G
GROUP BY AIRLINE) MUR;



--ON TIME PERCENTAGE FOR EACH AIRLINE FOR 2015.
SELECT A.AIRLINE,CASE WHEN IFNULL(TOTAL_ON_TIME,0) = 0 THEN 0 ELSE CAST((TOTAL_ON_TIME/TOTAL_FLIGHTS) * 100 AS NUMBER(5,2)) END PERCENT_ON_TIME
FROM(
SELECT F.AIRLINE_KEY, COUNT(*) TOTAL_FLIGHTS
FROM DW.FACT_FLIGHTS F
GROUP BY F.AIRLINE_KEY) TF
LEFT JOIN 
(SELECT F.AIRLINE_KEY, COUNT(*) TOTAL_ON_TIME
FROM DW.FACT_FLIGHTS F
 WHERE ARRIVAL_DELAY < 1
GROUP BY F.AIRLINE_KEY) OT ON TF.AIRLINE_KEY = OT.AIRLINE_KEY
JOIN DW.DIM_AIRLINES A ON TF.AIRLINE_KEY = A.AIRLINE_KEY
ORDER BY A.AIRLINE;


--CANCELLATION REASONS
SELECT A.AIRPORT
       ,MIN('DEPARTURE') AIRPORT_ORIGIN
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Airline/Carrier' THEN 1 ELSE 0 END) TOTAL_AIRLINE_CARRIER_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Weather' THEN 1 ELSE 0 END) TOTAL_WEATHER_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'National Air System' THEN 1 ELSE 0 END) TOTAL_NATIONAL_AIR_SYSTEM_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Security' THEN 1 ELSE 0 END) TOTAL_SECURITY_CANCELLATIONS
FROM DW.FACT_FLIGHTS F JOIN DW.DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_KEY = A.AIRPORT_KEY
WHERE F.CANCELLATION_REASON <> 'N/A'
GROUP BY A.AIRPORT
UNION ALL
SELECT A.AIRPORT
       ,MIN('DESTINATION') AIRPORT_ORIGIN
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Airline/Carrier' THEN 1 ELSE 0 END) TOTAL_AIRLINE_CARRIER_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Weather' THEN 1 ELSE 0 END) TOTAL_WEATHER_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'National Air System' THEN 1 ELSE 0 END) TOTAL_NATIONAL_AIR_SYSTEM_CANCELLATIONS
       ,SUM(CASE F.CANCELLATION_REASON WHEN 'Security' THEN 1 ELSE 0 END) TOTAL_SECURITY_CANCELLATIONS
FROM DW.FACT_FLIGHTS F JOIN DW.DIM_AIRPORTS A ON F.DESTINATION_AIRPORT_KEY = A.AIRPORT_KEY
WHERE F.CANCELLATION_REASON <> 'N/A'
GROUP BY A.AIRPORT
ORDER BY AIRPORT;


--TOTAL NUMBER OF FLIGHTS PER AIRLINE PER DEPARTURE AIRPORT.
SELECT A.AIRLINE, COUNT(*) TOTAL_FLIGHTS
FROM DW.FACT_FLIGHTS F
JOIN DW.DIM_AIRLINES A ON F.AIRLINE_KEY = A.AIRLINE_KEY
GROUP BY A.AIRLINE
ORDER BY A.AIRLINE;

--TOTAL NUMBER OF DELAYS.
SELECT AIRLINE
       ,TOTAL_DELAYS
       ,RANK() OVER(ORDER BY TOTAL_DELAYS DESC) RANK
FROM(
SELECT A.AIRLINE,COUNT(*) TOTAL_DELAYS
FROM DW.FACT_FLIGHTS F
JOIN DW.DIM_AIRLINES A ON F.AIRLINE_KEY = A.AIRLINE_KEY
WHERE (IFNULL(DEPARTURE_DELAY,0) > 0 or IFNULL(ARRIVAL_DELAY,0)> 0)
GROUP BY A.AIRLINE) D;
