CREATE WAREHOUSE INTERVIEW_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL'
MAX_CLUSTER_COUNT = 1
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE USER_XXXXX_XXXXX;

CREATE SCHEMA STAGE;
CREATE SCHEMA DW;


create or replace TABLE DW.DIM_AIRPORTS (
	AIRPORT_KEY NUMBER(38,0) NOT NULL,
	AIRPORT_CODE VARCHAR(16777216),
	AIRPORT VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	LATITUDE FLOAT,
	LONGITUDE FLOAT
);

create or replace TABLE DW.DIM_AIRLINES (
	AIRLINE_KEY NUMBER(38,0) NOT NULL,
	AIRLINE_CODE VARCHAR(16777216),
	AIRLINE VARCHAR(16777216)
);

create or replace TABLE DW.FACT_FLIGHTS (
	AIRLINE_KEY NUMBER(38,0) NOT NULL,
	AIRLINE_CODE VARCHAR(16777216),
	DEPARTURE_AIRPORT_KEY NUMBER(38,0) NOT NULL,
	DEPARTURE_AIRPORT_CODE VARCHAR(16777216),
	DESTINATION_AIRPORT_KEY NUMBER(38,0) NOT NULL,
	DESTINATION_AIRPORT_CODE VARCHAR(16777216),
	YEAR NUMBER(38,0),
	MONTH NUMBER(38,0),
	DAY NUMBER(38,0),
	FLIGHT_NUMBER NUMBER(38,0),
	TAIL_NUMBER VARCHAR(16777216),
	SCHEDULED_DEPARTURE NUMBER(38,0) NOT NULL,
	DEPARTURE_TIME NUMBER(38,0) NOT NULL,
	DEPARTURE_DELAY NUMBER(38,0) NOT NULL,
	TAXI_OUT NUMBER(38,0) NOT NULL,
	WHEELS_OFF NUMBER(38,0) NOT NULL,
	SCHEDULED_TIME NUMBER(38,0) NOT NULL,
	ELAPSED_TIME NUMBER(38,0) NOT NULL,
	AIR_TIME NUMBER(38,0) NOT NULL,
	DISTANCE NUMBER(38,0) NOT NULL,
	WHEELS_ON NUMBER(38,0) NOT NULL,
	TAXI_IN NUMBER(38,0) NOT NULL,
	SCHEDULED_ARRIVAL NUMBER(38,0) NOT NULL,
	ARRIVAL_TIME NUMBER(38,0) NOT NULL,
	ARRIVAL_DELAY NUMBER(38,0) NOT NULL,
	DIVERTED BOOLEAN NOT NULL,
	CANCELLED BOOLEAN NOT NULL,
	CANCELLATION_REASON VARCHAR(16777216) NOT NULL,
	AIR_SYSTEM_DELAY NUMBER(38,0) NOT NULL,
	SECURITY_DELAY NUMBER(38,0) NOT NULL,
	AIRLINE_DELAY NUMBER(38,0) NOT NULL,
	LATE_AIRCRAFT_DELAY NUMBER(38,0) NOT NULL,
	WEATHER_DELAY NUMBER(38,0)
);
